# Generated by Django 5.2 on 2026-02-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0005_alter_component_category_alter_component_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('for_sale', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('NOT_AVAILABLE', 'NOT_AVAILABLE'), ('ASK', 'ASK')], default='AVAILABLE', max_length=100)),
                ('components', models.ManyToManyField(related_name='pcbuilds_components', to='components.component')),
            ],
        ),
    ]
