# Generated by Django 5.2 on 2026-02-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
        ('components', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcbuild',
            name='components',
            field=models.ManyToManyField(related_name='pc_builds', to='components.component'),
        ),
    ]
