# Generated by Django 5.2 on 2026-02-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_alter_pcbuild_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcbuild',
            name='image',
            field=models.URLField(default='', null=True),
        ),
    ]
