# Generated by Django 5.2 on 2026-02-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.URLField(default='', null=True),
        ),
    ]
