# Generated by Django 5.2 on 2026-02-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_component_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('GAMING', 'GAMING'), ('BUDGET', 'BUDGET'), ('WORKSTATION', 'WORKSTATION'), ('OFFICE', 'OFFICE')], max_length=100),
        ),
    ]
