# Generated by Django 5.2 on 2026-02-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('GAMING', 'GAMING'), ('BUDGET', 'BUDGET'), ('WORKSTATION', 'WORKSTATION'), ('OFFICE', 'OFFICE')], default='WORKSTATION', max_length=100),
        ),
    ]
