# Generated by Django 5.2 on 2026-02-19 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_alter_category_description_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components_category', to='components.category'),
        ),
        migrations.AlterField(
            model_name='component',
            name='tags',
            field=models.ManyToManyField(related_name='components_tags', to='components.tag'),
        ),
    ]
