# Generated by Django 5.2 on 2026-02-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_alter_component_category_alter_component_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('CPU', 'Cpu'), ('GPU', 'Gpu'), ('PSU', 'Psu'), ('RAM', 'Ram'), ('SSD', 'Ssd'), ('HDD', 'Hdd'), ('MOTHERBOARD', 'Motherboard'), ('COOLER', 'Cooler'), ('CASE', 'Case')], default='CPU', max_length=100),
        ),
    ]
